# Generated by Django 3.1.5 on 2021-02-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210206_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
